### ISSUE TITLE
Write a formula for java-language-server It has dependencies maven & bazel (available in...

### ISSUE THREAD

**Issue by 0pdd** [frou/homebrew-tap#3]
The puzzle `0-f4d07437` from #0 has to be resolved: 

https://github.com/frou/homebrew-tap/blob/2b6833fbe72a1538c19e69195663f1f4769b45c8/Formula/java-language-server.rb#L1-L3

The puzzle was created by Duncan Holm on 27-Aug-19. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by frou** [comment]
Abandoning
